---
id: test-slide
base_name: slide-test
tags: []
presentation_date:
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1600
height: 900
source_code_uri:
author:
  markup_language: :rd
  name:
  email:
  rubygems_user:
  slideshare_user:
  speaker_deck_user:
